### ISSUE TITLE
[BACK] - API de listagem de vendas para vendedor

### ISSUE THREAD

**Issue by jonatasoli** [jonatasoli/fast-ecommerce-back#1090]
Ajustar a API para listar as vendas de um vendedor.

Será necessário modificar o fluxo do checkout

Na task checkout caso tenha um coupon será necessário ver se tem um affiliate_id
Se tiver um affiliate_id será necessário adicionar o affiliate_id em order

Será necessário criar uma task para alimentar a sales_comission

## Regra da sales_comission:
Na coluna user_id será o código do affiliate_id
Na coluna order_id será o código da order relacionado
Na coluna comission será um decimal com o valor da comissão do pedido
Na coluna date_created será a data daquele momento
Na coluna released será a data do now + 30 dias
Na coluna paid será default false.

Para gerar a comission será necessário calcular o subtotal do carrinho pois não será adicionado o frete, então vamos calcular o percentual da comissão.
subtotal * % de comissão

Será necessário na tabela coupon adicionar o percentual de comissão como Decimal.

Será necessário criar um job em python com sqlalchemy para verificar a data created de toda a tabela comission com data maior ou igual a 30 dias e paid false ai será feito um update com paid true para esses campos.

## Tag reports

[/report/user/comissions](http://localhost:8001/docs#/report/get_user_sales_comissions_report_user_comissions_get)
Vai receber o user_id e o status do pagamento se está paid como true or false e released também vai ser true or false.

## Vai retornar uma lista de commissions

Será necessário consultar a tablea sales_comission, order
Em order tem o affiliate_id que é o user_id do vendedor

exemplo 

``json
{
  "comissions": [
    {
      "order_id": 0,
      "user_name": "string",
      "commission": "string",
      "date_created": "2023-12-06T08:35:00.058Z",
      "released": true,
      "paid": true
    }
  ]
}
```

**Comment by ArturAntunes** [comment]
{
    "comissions": [
        {
            "order_id": 49,
            "user_id": 2,
            "commission": "1.062",
            "date_created": "2023-12-20T20:13:11.897494",
            "release_date": "2024-01-19T20:13:11.897494",
            "released": true,
            "paid": false
        }
    ]
}

retorno do endpoint
