### ISSUE TITLE
Voltar na listagem de produtos a quantidade em estoque

### ISSUE THREAD

**Issue by jonatasoli** [jonatasoli/fast-ecommerce-back#1134]
Nas rotas de produtos voltar a quantidade em estoque daquele produto.

**Comment by thaismtss** [comment]
Adicionar o retorno do estoque detro de cartItems na rota estimate 
![image](https://github.com/jonatasoli/fast-ecommerce-back/assets/69439044/f5b938e2-7960-481f-9da0-540cf00a2f1e)

**Comment by jonatasoli** [comment]
Beleza já to mexendo nessa rota, você só vai me fazer refatorar as queries kkk

**Comment by jonatasoli** [comment]
resolvido no commit:
bccf3e05e8d00adbb1dbea5db6b6d79b32a464c7
