### ISSUE TITLE
Erro para adicionar produtos no carrinho 

### ISSUE THREAD

**Issue by thaismtss** [jonatasoli/fast-ecommerce-back#1148]
[/cart/{uuid}/product](https://staging.api.gattorosa.com.br/docs#/cart/add_product_to_cart_cart__uuid__product_post)
Nessa rota ao adicionar um produto no carrinho o available_quantity está retornando como 0 mesmo o produto tendo estoque

Como simular:
Adicionar um produto no carrinho. 

![image](https://github.com/jonatasoli/fast-ecommerce-back/assets/69439044/d8ed6b3e-0667-4316-ab45-26199c2e2795)

**Comment by jonatasoli** [comment]
fi xin e25d888af100debe8eb8664cc0a2f0b3d20e34e0
